### PR TITLE
Filter categories by content languages

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes: #656 

Also fixes: the language count in settings, and a translations of drop downs in settings.

With this we filter down the categories to non empty ones, depending on the content language settings. Eg: setting it to German only (we won't have TED, which is currently only available in English):

Simulator Screenshot - iPhone 15 - 2024-02-18 at 09 21 49

### CODE REVIEW

**Review by rgaudin — DISMISSED** [review]
Looks OK to me but I'm in no capacity to review the code. Seems like behavior is what we want given it's a user-defined filter on languages.

**Review by kelson42 — CHANGES_REQUESTED** [review]
Please fix Codefactor.

**Comment by BPerlakiH** [comment]
> Please fix Codefactor.

Please see it updated.

**Comment by rgaudin** [comment]
@BPerlakiH @kelson42 forced-pushed and only requested codefactor to be fixed. You can merge

**Pull request merged**
