### PR TITLE
Switch to ISO-639-3 language codes everywhere

### LINKED ISSUE #667: Update 2 letters language code settings to 3 letters
Should applied just right after the new update (run once):
* on iOS15: based on an ad-hoc hardcoded mapping list of X importances languages codes, apply the update. If no matching is found, then remove the language code. If at the end, list of preferend languages is empty, will default to `eng`.
* on iOS16+: use native primitives to convert to 3 letters language code.

This piece code should be removed after a few additional releases:
* Create a dedicated issue for that
* Put clear comment in the code that this is temporary code

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes #667

### CODE REVIEW

**Review by rgaudin — DISMISSED** [review]
LGTM ; comments are really helpful 👍

**Comment by kelson42** [comment]
@BPerlakiH Please resolve conflicts. In the future, just base this branch/PR on the depending branch and not on `main` to avoid this kind of problem.

**Comment by BPerlakiH** [comment]
I've updated it.

**Comment by kelson42** [comment]
@BPerlakiH This is not rebased properly. Please learn how to do that properly.

**Comment by BPerlakiH** [comment]
I've updated it, now it looks better.

**Review by rgaudin — APPROVED** [review]

**Pull request merged**
