### PR TITLE
Remove default/enforced language code solution

### PR DESCRIPTION
**Pull request by BPerlakiH**
## The problem as of  #603 

Our former assumption was that if a language is enforced for a custom app, we need to force its selection from the available list of languages, to be the default one.

This assumption is no longer true.

What we want to do instead, is that if a language is enforced for a custom app, we only include this single language, and no other languages can be selected for this app. This means that we can handle this change on the project level, and no code change is required.

## Solution 

Remove the former changes in code, as they are no longer needed.

### CODE REVIEW

**Comment by kelson42** [comment]
@BPerlakiH Thank you. If it full fixes #603,lease write "Fixes #603" in the PR description. As PR title, please only write a synthetix description of what the PR does (so no related issue number).

**Comment by BPerlakiH** [comment]
Thank you, I have updated the PR title, pushed a fix for the CI build.
This PR is not directly solving the issue, the solution comes from the project file settings of the custom app (which is not part of the Kiwix/main). This PR is removing the unnecessary code that was introduced earlier for handling the language settings, which we no longer need.

**Comment by kelson42** [comment]
@BPerlakiH If i get it right, if we merge only this we will create actually a regression. So in which PR comes the full fix?

**Comment by BPerlakiH** [comment]
@kelson42 it won't cause a regression, as the solution to the problem is to include only the German language file in the DWDS app settings, which is outside of this repository. It's OK to merge this.

**Review by kelson42 — APPROVED** [review]

**Pull request merged**
