### PR TITLE
Introducing Continuous Integration

### LINKED ISSUE #159: Introduce Continous Integration
The current repository has neither a CI (Continuous Integration) nor a CD (Continuous Deployement).

This is unoptimal because:
* Without CI (testing the compilation, the app with a automated tests, a code coverage solution) we have no baseline security to avoid regressions
* Without CI, no CD is possible and the pushing of new releases relies fully on a developer doing manually the operation. A way of doing which is unsecure and create a SPOC at the developer in charge.
* Without CD, no nightly either
* A complementary problem of this is that this is not really feasible because the core libraries (libkiwix and libzim) are not prebuilt/prepackaged for macOS. This is a blocker for this task, but doing it properly
  * Secure the quality of the software (no manual configuration)
  * Simplify the build process which should allow to onboard new (junior) developer (a thing which is "impossible" for the moment due to the complexity and the requirement of another field of expertise which is needed by libzim/libkiwix compilation).

### PR DESCRIPTION
**Pull request by rgaudin**
Fixes #159

Building both macOS App and iOS App on every commit on `main` and on PRs.
Build is not used/uploaded but still requires to be signed.

⚠️ build command is ran up to twice as I didn't manage to reliably make it work otherwise. There are always `No module 'CoreKiwix'` errors.

Build is signed using an `Apple Development` certificate (in secrets)

### CODE REVIEW

**Comment by rgaudin** [comment]
⚠️ Awaiting tomorrow (2023-11-16) to change XCF_URL to nightly

**Review by kelson42 — APPROVED** [review]
LGTM to me.

Remarks:
* not sure what is this `ci` branch in the workflow!?
* should probably be rebased on `libkiwix-13` branch

**Comment by rgaudin** [comment]
>     * not sure what is this `ci` branch in the workflow!?

Was for testing the actions before the PR

>     * should probably be rebased on `libkiwix-13` branch

Targets it now

**Comment by kelson42** [comment]
All good with libkiwix `13.0.0`!

**Pull request merged**
