### PR TITLE
Fix first time build of the project

### LINKED ISSUE #613: Fix first time build
# The problem
If the project is checked out fresh (which is the case every single time on CI builds), it cannot be built right away.
Only the second time we build it, it will succeed.

# Cause
The module maps are copied into the CoreKiwix.xcframework as a building step.
We do this for every single build, although we really need to do it only once.
The real problem with this is that this step is carried out slightly late in the process, therefore the first build will fail, while subsequent builds will succeed.

# Solution

Move the copy module maps commands as a post step to downloading the CoreKiwix.xcframework, and remove it from the build steps.
This way the first build will succeed (and all the subsequent ones as well).

### PR DESCRIPTION
**Pull request by BPerlakiH**
Fixes #613

### CODE REVIEW

**Review by kelson42 — APPROVED** [review]
LGTM

**Comment by rgaudin** [comment]
@kelson42, I was asked to review this as well. 10h, during night time is too short. Especially considering there is no urgency regarding this ticket.

This PR lacks the removal of the hack/workaround in the workflows. @BPerlakiH please make another PR for it.

@kelson42 we should discuss this today. I think this should be in the xcframework. If we agree on this, we should discuss whether to put it in kiwix-build or libkiwix.

**Comment by BPerlakiH** [comment]
@rgaudin I understand your point. My point of view was a bit the other way around: 
As I tried to add the fastlane integration to do the building of the apps, I did not wanted to introduce a similar work around (with retries) to make the build green.
Since we are about to change the CI workflow, the retry work around will be cleaned up that way.

**Comment by BPerlakiH** [comment]
I do like the idea of putting it into the XCFramework, that would simplify this even more.

**Comment by rgaudin** [comment]
> Since we are about to change the CI workflow, the retry work around will be cleaned up that way.

OK 👍

**Comment by rgaudin** [comment]
> I do like the idea of putting it into the XCFramework, that would simplify this even more.

We've agreed on this with @mgautierfr and @kelson42 ; I'll make a PR and we'll have it in XCF for the next version

**Pull request merged**
